## 'Calculating Expected Offspring'

**Connections**: `IPRB`

---


**Given**: Six nonnegative integers, each of which does not exceed 20,000. The integers correspond to the number of couples in a population possessing each genotype pairing for a given factor. In order, the six given integers represent the number of couples having the following genotypes:

- AA-AA
- AA-Aa
- AA-aa
- Aa-Aa
- Aa-aa
- aa-aa

**Return**: The expected number of offspring displaying the dominant phenotype in the next generation, under the assumption that every couple has exactly two offspring.

*Notes*:


In [19]:
# Libraries to load

import numpy as np


In [24]:
def progeny_distribution_matrix():
    '''
    3x6 matrix with rows as either DD, Dd, or dd for progeny, and columns the six parental pairs:
            _DD-DD_|_DD-Dd_|_DD-dd_|_Dd-Dd_|_Dd-dd_|_dd-dd_|
        DD |       |       |       |       |       |       |
        Dd |       |       |       |       |       |       |
        dd |       |       |       |       |       |       |
           -------------------------------------------------
    '''
    return np.array([
        [1.00, 0.50, 0.00, 0.25, 0.00, 0.00],
        [0.00, 0.50, 1.00, 0.50, 0.50, 0.00],
        [0.00, 0.00, 0.00, 0.25, 0.50, 1.00]
    ])


def progeny_genotype_distribution(parent_list, pgmatrix):
    '''
    text
    '''
    return np.matmul(pgmatrix, 2*np.transpose(np.array(parent_list)))

    

In [25]:
progeny_genotype_distribution([1, 0, 0, 1, 0, 1], 
                              progeny_distribution_matrix())


array([2.5, 1. , 2.5])

In [26]:
progeny_genotype_distribution([2, 3, 1, 1, 5, 2], 
                              progeny_distribution_matrix())


array([ 7.5, 11. ,  9.5])

In [29]:
infile = open('datasets/rosalind_iev_attempt01.txt','r')
lst    = infile.read().rstrip('\n').split(' ')
lst    = [int(i) for i in lst]
infile.close()

print(2*sum(lst))
X = progeny_genotype_distribution(lst, progeny_distribution_matrix())
print(X)
print(sum(X))
print(X[0]+X[1])

del lst, X

215770
[64232.5 91120.  60417.5]
215770.0
155352.5


---

### Problem Attempt:

#### Attempt 1

In [ ]:
infile = open('datasets/rosalind_iev.txt','r')
lst    = infile.read().rstrip('\n').split(' ')
lst    = [int(i) for i in lst]
infile.close()


In [ ]:
print( progeny_phenotype(progeny_genotype(lst), output_type='dom') )


In [ ]:
progeny_genotype(lst)

In [ ]:
x = 0
for i in lst:
    x+=i
print('Total parent population: ', x)
print('Expected offspring population: ', int(2*x))

print('Current number of expected dominant phenotypes: ', int(2*x)*progeny_phenotype(progeny_genotype(lst), output_type='dom'))

del x

---

#### Attempt 2

In [31]:
infile = open('datasets/rosalind_iev.txt','r')
lst    = infile.read().rstrip('\n').split(' ')
lst    = [int(i) for i in lst]
infile.close()

X = progeny_genotype_distribution(lst, progeny_distribution_matrix())

print(X[0]+X[1])

del lst, X

152627.5
